//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosManejo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacionpedido
    {
        public int AsignacionID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public Nullable<int> RepartidorID { get; set; }
        public string Estado { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual repartidor repartidor { get; set; }
    }
}
