//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosManejo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallepedido
    {
        public int DetallePedidoID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual menu menu { get; set; }
    }
}
