//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosManejo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int FacturaID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string MetodoPago { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
