//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosManejo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialpedido
    {
        public int HistorialID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public string EstadoAnterior { get; set; }
        public string EstadoNuevo { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> UsuarioModificadorID { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
