//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosManejo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLmanejopedidosEntities1 : DbContext
    {
        public SQLmanejopedidosEntities1()
            : base("name=SQLmanejopedidosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignacionpedido> asignacionpedido { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detallepedido> detallepedido { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<historialpedido> historialpedido { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<repartidor> repartidor { get; set; }
        public virtual DbSet<restaurante> restaurante { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
    }
}
